### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by jungle-boogie** [thibaud-rohmer/PhotoLight#2]
What license is your application licensed under?

**Comment by thibaud-rohmer** [comment]
Hi, as written in index.php : 
- PhotoLight is free software: you can redistribute it and/or modify
- it under the terms of the GNU General Public License as published by
- the Free Software Foundation, either version 3 of the License, or
- (at your option) any later version.
  *
- PhotoLight is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty of
- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- GNU General Public License for more details.
  *
- You should have received a copy of the GNU General Public License
- along with PhotoLight.  If not, see http://www.gnu.org/licenses/.

**Comment by jungle-boogie** [comment]
Hello,

Thank you.

Your project is listed here: https://github.com/Kickball/awesome-selfhosted

**Comment by thibaud-rohmer** [comment]
Cool ! Thanks !
